server:
  port: 8083   # HTTP (Tomcat) port
spring:
  profiles:
  active: a
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: user
    password: l123456
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
